# Generated by Django 2.2.12 on 2020-05-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200518_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(blank=True, default='defaults/blog_cover.jpg', upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='feature_image',
            field=models.ImageField(blank=True, default='defaults/blog_featured.jpg', upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default='defaults/blog_thumbnail.jpg', upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_small',
            field=models.ImageField(blank=True, default='defaults/blog_small_thumnnail.jpg', upload_to='posts/'),
        ),
    ]
