# Generated by Django 2.2.12 on 2020-05-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200518_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='postview',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
